In [19]:
import pandas as pd

link = 'https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/imdb_1000.csv'
df = pd.read_csv(link)

In [20]:
# Map used for substituting each value in a Series with another value, here replace series by str

df['actors_list'] = df['actors_list'].map(str)

In [21]:
#create a loop for cleaning base with replace [ and u and ' and ]...

for i in range(len(df['actors_list'])):
    df['actors_list'][i] = df['actors_list'][i].replace("[u\'", "").replace("u\'", "").replace("\'", '').replace("]","").replace("u\"", "").replace("\"", "")
    
df

C:\Users\cathe\AppData\Local\Temp/ipykernel_68/2628048337.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['actors_list'][i] = df['actors_list'][i].replace("[u\'", "").replace("u\'", "").replace("\'", '').replace("]","").replace("u\"", "").replace("\"", "")

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"Tim Robbins, Morgan Freeman, Bob Gunton"
1,9.2,The Godfather,R,Crime,175,"Marlon Brando, Al Pacino, James Caan"
2,9.1,The Godfather: Part II,R,Crime,200,"Al Pacino, Robert De Niro, Robert Duvall"
3,9.0,The Dark Knight,PG-13,Action,152,"Christian Bale, Heath Ledger, Aaron Eckhart"
4,8.9,Pulp Fiction,R,Crime,154,"John Travolta, Uma Thurman, Samuel L. Jackson"
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"Dustin Hoffman, Jessica Lange, Teri Garr"
975,7.4,Back to the Future Part III,PG,Adventure,118,"Michael J. Fox, Christopher Lloyd, Mary Steenb..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"Russell Crowe, Paul Bettany, Billy Boyd"
977,7.4,Poltergeist,PG,Horror,114,"JoBeth Williams, Heather ORourke, Craig T. Nelson"
978,7.4,Wall Street,R,Crime,126,"Charlie Sheen, Michael Douglas, Tamara Tunie"

In [22]:
# split before explode

df['actors_list'] = df['actors_list'].str.split(",")
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[Tim Robbins, Morgan Freeman, Bob Gunton]"
1,9.2,The Godfather,R,Crime,175,"[Marlon Brando, Al Pacino, James Caan]"
2,9.1,The Godfather: Part II,R,Crime,200,"[Al Pacino, Robert De Niro, Robert Duvall]"
3,9.0,The Dark Knight,PG-13,Action,152,"[Christian Bale, Heath Ledger, Aaron Eckhart]"
4,8.9,Pulp Fiction,R,Crime,154,"[John Travolta, Uma Thurman, Samuel L. Jackson]"
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[Dustin Hoffman, Jessica Lange, Teri Garr]"
975,7.4,Back to the Future Part III,PG,Adventure,118,"[Michael J. Fox, Christopher Lloyd, Mary Ste..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[Russell Crowe, Paul Bettany, Billy Boyd]"
977,7.4,Poltergeist,PG,Horror,114,"[JoBeth Williams, Heather ORourke, Craig T. ..."
978,7.4,Wall Street,R,Crime,126,"[Charlie Sheen, Michael Douglas, Tamara Tunie]"

In [23]:
# explode for one row with one value of actors_list column

df = df.explode('actors_list')
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,Tim Robbins
0,9.3,The Shawshank Redemption,R,Crime,142,Morgan Freeman
0,9.3,The Shawshank Redemption,R,Crime,142,Bob Gunton
1,9.2,The Godfather,R,Crime,175,Marlon Brando
1,9.2,The Godfather,R,Crime,175,Al Pacino
...,...,...,...,...,...,...
977,7.4,Poltergeist,PG,Horror,114,Heather ORourke
977,7.4,Poltergeist,PG,Horror,114,Craig T. Nelson
978,7.4,Wall Street,R,Crime,126,Charlie Sheen
978,7.4,Wall Street,R,Crime,126,Michael Douglas
978,7.4,Wall Street,R,Crime,126,Tamara Tunie

In [24]:
#reset index for df

df = df.reset_index(drop=True)
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,Tim Robbins
1,9.3,The Shawshank Redemption,R,Crime,142,Morgan Freeman
2,9.3,The Shawshank Redemption,R,Crime,142,Bob Gunton
3,9.2,The Godfather,R,Crime,175,Marlon Brando
4,9.2,The Godfather,R,Crime,175,Al Pacino
...,...,...,...,...,...,...
2932,7.4,Poltergeist,PG,Horror,114,Heather ORourke
2933,7.4,Poltergeist,PG,Horror,114,Craig T. Nelson
2934,7.4,Wall Street,R,Crime,126,Charlie Sheen
2935,7.4,Wall Street,R,Crime,126,Michael Douglas
2936,7.4,Wall Street,R,Crime,126,Tamara Tunie

In [25]:
#check 
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,Tim Robbins
1,9.3,The Shawshank Redemption,R,Crime,142,Morgan Freeman
2,9.3,The Shawshank Redemption,R,Crime,142,Bob Gunton
3,9.2,The Godfather,R,Crime,175,Marlon Brando
4,9.2,The Godfather,R,Crime,175,Al Pacino
...,...,...,...,...,...,...
2932,7.4,Poltergeist,PG,Horror,114,Heather ORourke
2933,7.4,Poltergeist,PG,Horror,114,Craig T. Nelson
2934,7.4,Wall Street,R,Crime,126,Charlie Sheen
2935,7.4,Wall Street,R,Crime,126,Michael Douglas
2936,7.4,Wall Street,R,Crime,126,Tamara Tunie

In [26]:
# Which actor is mentionned most often ?
df['actors_list'].value_counts().idxmax()

'Robert De Niro'

In [27]:
f"The actor is mentioned the most often is {df['actors_list'].value_counts().idxmax()}"

'The actor is mentioned the most often is Robert De Niro'